Repository rive-app/rive-tizen, pull requests merged in 2021-03, with the labels that each got.

#5 Implements ThorVG Renderer Skeletone Code for Rive
  example/meson.build
  example/rive_viewer.cpp
  example/shapes.riv
  meson.build
  src/renderer/include/thorvg_renderer.hpp
  src/renderer/include/to_thorvg.hpp
  src/renderer/src/thorvg_renderer.cpp
  src/rive_tizen.cpp
Labels: enhancement

#7 Implements stroke feature for shape pathes
  example/shapes.riv
  src/renderer/include/thorvg_renderer.hpp
  src/renderer/src/thorvg_renderer.cpp
Labels: enhancement

#8 renderer: add tvg stroke and cap function
  src/renderer/include/thorvg_renderer.hpp
  src/renderer/src/thorvg_renderer.cpp
Labels: enhancement

#9 renderer, example: implments shape animation
  example/rive_viewer.cpp
  example/shapes.riv
  src/renderer/include/thorvg_renderer.hpp
  src/renderer/src/thorvg_renderer.cpp
Labels: enhancement

#19 build: add example build option to toggle it.
  meson.build
  meson_options.txt
Labels: infrastructure

#22 example: code refactoring
  example/rive_viewer.cpp
Labels: refactoring

#23 build: revise meson build script
  example/meson.build
  example/rive_viewer.cpp
  inc/meson.build
  meson.build
  src/meson.build
  src/renderer/meson.build
  src/renderer/tvg_renderer.cpp
  src/renderer/tvg_renderer.hpp
Labels: infrastructure

#25 remove a redundant file.
  build.sh
Labels: infrastructure

#24 replace rive-cpp submodule with original repo.
  .gitmodules
Labels: infrastructure

#26 renderer: implements trimpath and artboard rendering
  src/renderer/tvg_renderer.cpp
  src/renderer/tvg_renderer.hpp
Labels: enhancement

#27 example: add space_reload.riv resource
  example/resource/gradation_space_reload.riv
Labels: infrastructure

#28 renderer: fix wrong layering order.
  example/rive_viewer.cpp
  src/renderer/tvg_renderer.cpp
Labels: bug

#29 renderer: code refactoring.
  src/renderer/tvg_renderer.cpp
  src/renderer/tvg_renderer.hpp
Labels: refactoring

#30 renderer: optimize path manipulation.
  src/renderer/tvg_renderer.cpp
  src/renderer/tvg_renderer.hpp
Labels: optimization

#31 renderer: code refactoring
  src/renderer/tvg_renderer.cpp
  src/renderer/tvg_renderer.hpp
Labels: refactoring
